(function () {
  const rules = [
    {
      id: "meteor_coupon",
      title: "Meteor Coupon",
      description: "Instantly removes the farthest rival stone from the origin.",
      trigger: "instant",
      effect: "remove",
      target: "ruleOpponents",
      selector: "farthestOrigin",
      count: 1
    },
    {
      id: "home_inspection",
      title: "Home Inspection",
      description: "Instantly removes the rival stone closest to the origin.",
      trigger: "instant",
      effect: "remove",
      target: "ruleOpponents",
      selector: "nearestOrigin",
      count: 1
    },
    {
      id: "cutting_room",
      title: "Cutting Room",
      description: "Instantly removes one random stone from the board.",
      trigger: "instant",
      effect: "remove",
      target: "all",
      selector: "random",
      count: 1
    },
    {
      id: "spring_cleaning",
      title: "Spring Cleaning",
      description: "Instantly removes the oldest rival stone.",
      trigger: "instant",
      effect: "remove",
      target: "ruleOpponents",
      selector: "oldest",
      count: 1
    },
    {
      id: "fresh_paint",
      title: "Fresh Paint",
      description: "Instantly converts one random rival stone to your color.",
      trigger: "instant",
      effect: "convert",
      target: "ruleOpponents",
      selector: "random",
      count: 1,
      convertTo: "ruleOwner"
    },
    {
      id: "hostile_takeover",
      title: "Hostile Takeover",
      description: "Instantly converts the rival stone nearest to your last placement.",
      trigger: "instant",
      effect: "convert",
      target: "ruleOpponents",
      selector: "nearAnchor",
      anchor: "lastRuleOwner",
      count: 1,
      convertTo: "ruleOwner"
    },
    {
      id: "emergency_clone",
      title: "Emergency Clone",
      description: "Instantly adds two of your stones beside your last placement if space exists.",
      trigger: "instant",
      effect: "spawn",
      spawnOwner: "ruleOwner",
      spawnNear: "lastRuleOwner",
      count: 2
    },
    {
      id: "mirror_coupon",
      title: "Mirror Coupon",
      description: "Instantly adds one of your stones at the mirror of your last placement if open.",
      trigger: "instant",
      effect: "spawn",
      spawnOwner: "ruleOwner",
      spawnNear: "mirrorLastRuleOwner",
      count: 1
    },
    {
      id: "center_grant",
      title: "Center Grant",
      description: "Instantly adds one of your stones near the origin.",
      trigger: "instant",
      effect: "spawn",
      spawnOwner: "ruleOwner",
      spawnNear: "origin",
      count: 1
    },
    {
      id: "bubble_wrap",
      title: "Bubble Wrap",
      description: "Instantly shields your two newest stones from their next removal.",
      trigger: "instant",
      effect: "shield",
      target: "ruleOwner",
      selector: "newest",
      count: 2
    },
    {
      id: "swap_meet",
      title: "Swap Meet",
      description: "Instantly swaps two random stones on the board.",
      trigger: "instant",
      effect: "swapPositions",
      target: "all",
      selector: "random",
      count: 2
    },
    {
      id: "paint_mixer",
      title: "Paint Mixer",
      description: "Instantly swaps the owners of two random stones.",
      trigger: "instant",
      effect: "swapOwners",
      target: "all",
      selector: "random",
      count: 2
    },
    {
      id: "frontier_bailout",
      title: "Frontier Bailout",
      description: "Instantly shields your farthest stone and adds a neighbour if open.",
      trigger: "instant",
      effect: "shieldAndSpawn",
      target: "ruleOwner",
      selector: "farthestOrigin",
      count: 1,
      spawnOwner: "ruleOwner"
    },
    {
      id: "eviction_notice",
      title: "Eviction Notice",
      description: "Instantly pushes up to three rival stones one space away from the origin.",
      trigger: "instant",
      effect: "move",
      target: "ruleOpponents",
      selector: "nearestOrigin",
      movement: "outward",
      count: 3
    },
    {
      id: "gravity_receipt",
      title: "Gravity Receipt",
      description: "Instantly pulls up to three of your farthest stones toward the origin.",
      trigger: "instant",
      effect: "move",
      target: "ruleOwner",
      selector: "farthestOrigin",
      movement: "inward",
      count: 3
    },
    {
      id: "nesting_instinct",
      title: "Nesting Instinct",
      description: "For a few turns, each of your placements adds a friendly neighbour if open.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "spawn",
      spawnOwner: "triggerOwner",
      spawnNear: "lastPlacement",
      count: 1,
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "contagious_claim",
      title: "Contagious Claim",
      description: "For a few turns, each of your placements converts one adjacent rival stone.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "convert",
      target: "triggerOpponents",
      selector: "adjacentAnchor",
      anchor: "lastPlacement",
      count: 1,
      convertTo: "triggerOwner",
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "polite_echo",
      title: "Polite Echo",
      description: "For a few turns, each of your placements also tries to place its mirror.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "spawn",
      spawnOwner: "triggerOwner",
      spawnNear: "mirrorLastPlacement",
      count: 1,
      minTurns: 3,
      maxTurns: 6
    },
    {
      id: "safety_helmet",
      title: "Safety Helmet",
      description: "For a few turns, each of your newly placed stones gets a one-hit shield.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "shieldPlaced",
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "adjacent_audit",
      title: "Adjacent Audit",
      description: "For a few turns, your placements remove one adjacent rival stone.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "remove",
      target: "triggerOpponents",
      selector: "adjacentAnchor",
      anchor: "lastPlacement",
      count: 1,
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "spiteful_receipts",
      title: "Spiteful Receipts",
      description: "For a few turns, rival placements near your stones may convert one adjacent stone to you.",
      trigger: "afterPlacement",
      triggerScope: "opponentsOfRuleOwner",
      effect: "convert",
      target: "triggerOwner",
      selector: "adjacentAnchor",
      anchor: "lastPlacement",
      count: 1,
      convertTo: "ruleOwner",
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "quicklime",
      title: "Quicklime",
      description: "For a few turns, your placements push adjacent rival stones outward.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "move",
      target: "triggerOpponents",
      selector: "adjacentAnchor",
      anchor: "lastPlacement",
      movement: "outward",
      count: 2,
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "follow_the_leader",
      title: "Follow the Leader",
      description: "For a few turns, your oldest stone slides toward each new placement.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "move",
      target: "triggerOwner",
      selector: "oldest",
      anchor: "lastPlacement",
      movement: "towardsAnchor",
      count: 1,
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "reverse_sponsor",
      title: "Reverse Sponsor",
      description: "For a few turns, rival placements give you one stone beside their placement.",
      trigger: "afterPlacement",
      triggerScope: "opponentsOfRuleOwner",
      effect: "spawn",
      spawnOwner: "ruleOwner",
      spawnNear: "lastPlacement",
      count: 1,
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "toll_booth",
      title: "Toll Booth",
      description: "For a few turns, rival placements shield your nearest stone.",
      trigger: "afterPlacement",
      triggerScope: "opponentsOfRuleOwner",
      effect: "shield",
      target: "ruleOwner",
      selector: "nearAnchor",
      anchor: "lastPlacement",
      count: 1,
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "soft_launch",
      title: "Soft Launch",
      description: "For a few turns, your placements move one of your farthest stones outward.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "move",
      target: "triggerOwner",
      selector: "farthestOrigin",
      movement: "outward",
      count: 1,
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "stamp_collector",
      title: "Stamp Collector",
      description: "For a few turns, your placements convert one rival stone nearest the origin.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "convert",
      target: "triggerOpponents",
      selector: "nearestOrigin",
      count: 1,
      convertTo: "triggerOwner",
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "margin_notes",
      title: "Margin Notes",
      description: "For a few turns, your placements add a stone near the board edge of your color.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "spawn",
      spawnOwner: "triggerOwner",
      spawnNear: "farthestTriggerOwner",
      count: 1,
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "redistricting",
      title: "Redistricting",
      description: "For a few turns, your placements swap owners between two nearby stones.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "swapOwners",
      target: "all",
      selector: "nearAnchor",
      anchor: "lastPlacement",
      count: 2,
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "paper_shield",
      title: "Paper Shield",
      description: "For a few turns, every placement shields the placed stone, no matter who made it.",
      trigger: "afterPlacement",
      triggerScope: "all",
      effect: "shieldPlaced",
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "high_tide",
      title: "High Tide",
      description: "At each turn end, two of your nearest stones drift away from the origin.",
      trigger: "endTurn",
      effect: "move",
      target: "ruleOwner",
      selector: "nearestOrigin",
      movement: "outward",
      count: 2,
      minTurns: 4,
      maxTurns: 7
    },
    {
      id: "gravity_well",
      title: "Gravity Well",
      description: "At each turn end, two rival frontier stones drift toward the origin.",
      trigger: "endTurn",
      effect: "move",
      target: "ruleOpponents",
      selector: "farthestOrigin",
      movement: "inward",
      count: 2,
      minTurns: 4,
      maxTurns: 7
    },
    {
      id: "audit_the_oldest",
      title: "Audit the Oldest",
      description: "At each turn end, your oldest stone is shielded and the oldest rival stone is removed.",
      trigger: "endTurn",
      effect: "shieldAndRemove",
      target: "ruleOwner",
      selector: "oldest",
      removeTarget: "ruleOpponents",
      removeSelector: "oldest",
      count: 1,
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "frontier_tax",
      title: "Frontier Tax",
      description: "At each turn end, the farthest rival stone is removed.",
      trigger: "endTurn",
      effect: "remove",
      target: "ruleOpponents",
      selector: "farthestOrigin",
      count: 1,
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "reinforcement_drum",
      title: "Reinforcement Drum",
      description: "At each turn end, you add one stone beside your newest stone if open.",
      trigger: "endTurn",
      effect: "spawn",
      spawnOwner: "ruleOwner",
      spawnNear: "newestRuleOwner",
      count: 1,
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "conversion_audit",
      title: "Conversion Audit",
      description: "At each turn end, one rival stone nearest your last placement converts to you.",
      trigger: "endTurn",
      effect: "convert",
      target: "ruleOpponents",
      selector: "nearAnchor",
      anchor: "lastRuleOwner",
      count: 1,
      convertTo: "ruleOwner",
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "shield_cycle",
      title: "Shield Cycle",
      description: "At each turn end, your newest unshielded stone gains a one-hit shield.",
      trigger: "endTurn",
      effect: "shield",
      target: "ruleOwner",
      selector: "newest",
      count: 1,
      minTurns: 5,
      maxTurns: 7
    },
    {
      id: "board_shuffle",
      title: "Board Shuffle",
      description: "At each turn end, two random stones swap positions.",
      trigger: "endTurn",
      effect: "swapPositions",
      target: "all",
      selector: "random",
      count: 2,
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "ownership_drift",
      title: "Ownership Drift",
      description: "At each turn end, two random stones swap owners.",
      trigger: "endTurn",
      effect: "swapOwners",
      target: "all",
      selector: "random",
      count: 2,
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "center_pressure",
      title: "Center Pressure",
      description: "At each turn end, the nearest rival stone to the origin converts to you.",
      trigger: "endTurn",
      effect: "convert",
      target: "ruleOpponents",
      selector: "nearestOrigin",
      count: 1,
      convertTo: "ruleOwner",
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "paperwork_lantern",
      title: "Paperwork Lantern",
      description: "At each turn end, one of your farthest stones is shielded and pushed outward.",
      trigger: "endTurn",
      effect: "shieldAndMove",
      target: "ruleOwner",
      selector: "farthestOrigin",
      movement: "outward",
      count: 1,
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "quiet_annexation",
      title: "Quiet Annexation",
      description: "At each turn end, one rival stone adjacent to yours converts to you if one exists.",
      trigger: "endTurn",
      effect: "convert",
      target: "ruleOpponents",
      selector: "nearAnchor",
      anchor: "newestRuleOwner",
      count: 1,
      convertTo: "ruleOwner",
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "loose_change",
      title: "Loose Change",
      description: "At each turn end, add one stone near the oldest stone on the board for that stone's owner.",
      trigger: "endTurn",
      effect: "spawnFromSelectedOwner",
      target: "all",
      selector: "oldest",
      count: 1,
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "pressure_washer",
      title: "Pressure Washer",
      description: "At each turn end, two stones nearest your last placement slide away from it.",
      trigger: "endTurn",
      effect: "move",
      target: "all",
      selector: "nearAnchor",
      anchor: "lastRuleOwner",
      movement: "awayAnchor",
      count: 2,
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "magnet_notes",
      title: "Magnet Notes",
      description: "At each turn end, two of your stones move toward your newest stone.",
      trigger: "endTurn",
      effect: "move",
      target: "ruleOwner",
      selector: "farthestAnchor",
      anchor: "newestRuleOwner",
      movement: "towardsAnchor",
      count: 2,
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "no_center_parking",
      title: "No Center Parking",
      description: "For several turns, empty spaces within distance 1 of the origin cannot be placed on.",
      trigger: "static",
      effect: "block",
      pattern: { type: "centerRadius", radius: 1 },
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "outer_permit_office",
      title: "Outer Permit Office",
      description: "For several turns, spaces at distance 9 or farther from the origin are blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "outerRadius", radius: 9 },
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "odd_address_day",
      title: "Odd Address Day",
      description: "For several turns, odd-distance spaces are blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "distanceMod", modulus: 2, remainder: 1 },
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "even_address_day",
      title: "Even Address Day",
      description: "For several turns, even-distance spaces outside the origin are blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "distanceMod", modulus: 2, remainder: 0, ignoreOrigin: true },
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "blue_diagonal_tape",
      title: "Blue Diagonal Tape",
      description: "For several turns, every third q-diagonal is blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "axisMod", axis: "q", modulus: 3, remainder: 0 },
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "red_diagonal_tape",
      title: "Red Diagonal Tape",
      description: "For several turns, every third r-diagonal is blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "axisMod", axis: "r", modulus: 3, remainder: 0 },
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "shadow_diagonal_tape",
      title: "Shadow Diagonal Tape",
      description: "For several turns, every third s-diagonal is blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "axisMod", axis: "s", modulus: 3, remainder: 0 },
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "northwest_quarantine",
      title: "Northwest Quarantine",
      description: "For several turns, spaces with negative q and negative r are blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "quadrant", qSign: -1, rSign: -1 },
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "southeast_quarantine",
      title: "Southeast Quarantine",
      description: "For several turns, spaces with positive q and positive r are blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "quadrant", qSign: 1, rSign: 1 },
      minTurns: 3,
      maxTurns: 5
    },
    {
      id: "checkerboard_union",
      title: "Checkerboard Union",
      description: "For several turns, spaces where q plus r is even are blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "sumMod", modulus: 2, remainder: 0 },
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "checkerboard_management",
      title: "Checkerboard Management",
      description: "For several turns, spaces where q plus r is odd are blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "sumMod", modulus: 2, remainder: 1 },
      minTurns: 3,
      maxTurns: 4
    },
    {
      id: "ring_road_closure",
      title: "Ring Road Closure",
      description: "For several turns, distance 4 spaces are blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "distanceEquals", distance: 4 },
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "outer_ring_road",
      title: "Outer Ring Road",
      description: "For several turns, distance 7 spaces are blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "distanceEquals", distance: 7 },
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "triple_stamp_zone",
      title: "Triple Stamp Zone",
      description: "For several turns, spaces whose q minus r is divisible by 3 are blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "diffMod", modulus: 3, remainder: 0 },
      minTurns: 4,
      maxTurns: 6
    },
    {
      id: "lane_merger",
      title: "Lane Merger",
      description: "For several turns, the q equals r lane is blocked.",
      trigger: "static",
      effect: "block",
      pattern: { type: "diagonalEquals" },
      minTurns: 4,
      maxTurns: 6
    }
  ];

  const eachPlayerRuleIds = new Set([
    "meteor_coupon",
    "home_inspection",
    "spring_cleaning",
    "fresh_paint",
    "hostile_takeover",
    "emergency_clone",
    "mirror_coupon",
    "center_grant",
    "bubble_wrap",
    "frontier_bailout",
    "eviction_notice",
    "gravity_receipt",
    "high_tide",
    "gravity_well",
    "audit_the_oldest",
    "frontier_tax",
    "reinforcement_drum",
    "conversion_audit",
    "shield_cycle",
    "center_pressure",
    "paperwork_lantern",
    "quiet_annexation",
    "pressure_washer",
    "magnet_notes"
  ]);

  for (const rule of rules) {
    if (eachPlayerRuleIds.has(rule.id)) {
      rule.eachPlayer = true;
    }
  }

  if (typeof window !== "undefined") {
    window.HexTicTacToeChaosRules = rules;
  }

  if (typeof module !== "undefined") {
    module.exports = rules;
  }
}());
